// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/version_history/presentation/providers/version_history_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:educv/features/version_history/domain/version_history_repository.dart'
    as _i3;
import 'package:educv/features/version_history/models/version_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCVVersionModel_0 extends _i1.SmartFake
    implements _i2.CVVersionModel {
  _FakeCVVersionModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVersionComparisonModel_1 extends _i1.SmartFake
    implements _i2.VersionComparisonModel {
  _FakeVersionComparisonModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVersionStatsModel_2 extends _i1.SmartFake
    implements _i2.VersionStatsModel {
  _FakeVersionStatsModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VersionHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVersionHistoryRepository extends _i1.Mock
    implements _i3.VersionHistoryRepository {
  MockVersionHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CVVersionModel>> getVersionHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersionHistory,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CVVersionModel>>.value(<_i2.CVVersionModel>[]),
      ) as _i4.Future<List<_i2.CVVersionModel>>);

  @override
  _i4.Future<_i2.CVVersionModel> getVersion(String? versionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersion,
          [versionId],
        ),
        returnValue: _i4.Future<_i2.CVVersionModel>.value(_FakeCVVersionModel_0(
          this,
          Invocation.method(
            #getVersion,
            [versionId],
          ),
        )),
      ) as _i4.Future<_i2.CVVersionModel>);

  @override
  _i4.Future<_i2.VersionComparisonModel> compareVersions(
    int? fromVersion,
    int? toVersion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareVersions,
          [
            fromVersion,
            toVersion,
          ],
        ),
        returnValue: _i4.Future<_i2.VersionComparisonModel>.value(
            _FakeVersionComparisonModel_1(
          this,
          Invocation.method(
            #compareVersions,
            [
              fromVersion,
              toVersion,
            ],
          ),
        )),
      ) as _i4.Future<_i2.VersionComparisonModel>);

  @override
  _i4.Future<_i2.CVVersionModel> restoreVersion(int? versionNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreVersion,
          [versionNumber],
        ),
        returnValue: _i4.Future<_i2.CVVersionModel>.value(_FakeCVVersionModel_0(
          this,
          Invocation.method(
            #restoreVersion,
            [versionNumber],
          ),
        )),
      ) as _i4.Future<_i2.CVVersionModel>);

  @override
  _i4.Future<_i2.VersionStatsModel> getVersionStats() => (super.noSuchMethod(
        Invocation.method(
          #getVersionStats,
          [],
        ),
        returnValue:
            _i4.Future<_i2.VersionStatsModel>.value(_FakeVersionStatsModel_2(
          this,
          Invocation.method(
            #getVersionStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.VersionStatsModel>);
}
