// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/workflow/workflow_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:educv/features/workflow/data/models/workflow_models.dart'
    as _i2;
import 'package:educv/features/workflow/domain/workflow_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkflowInstanceModel_0 extends _i1.SmartFake
    implements _i2.WorkflowInstanceModel {
  _FakeWorkflowInstanceModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkflowConfigurationModel_1 extends _i1.SmartFake
    implements _i2.WorkflowConfigurationModel {
  _FakeWorkflowConfigurationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkflowDashboardModel_2 extends _i1.SmartFake
    implements _i2.WorkflowDashboardModel {
  _FakeWorkflowDashboardModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkflowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkflowRepository extends _i1.Mock
    implements _i3.WorkflowRepository {
  MockWorkflowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WorkflowInstanceModel?> getCVWorkflow(String? cvId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCVWorkflow,
          [cvId],
        ),
        returnValue: _i4.Future<_i2.WorkflowInstanceModel?>.value(),
      ) as _i4.Future<_i2.WorkflowInstanceModel?>);

  @override
  _i4.Future<_i2.WorkflowInstanceModel> getWorkflowInstance(
          String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowInstance,
          [instanceId],
        ),
        returnValue: _i4.Future<_i2.WorkflowInstanceModel>.value(
            _FakeWorkflowInstanceModel_0(
          this,
          Invocation.method(
            #getWorkflowInstance,
            [instanceId],
          ),
        )),
      ) as _i4.Future<_i2.WorkflowInstanceModel>);

  @override
  _i4.Future<List<_i2.WorkflowInstanceModel>> getWorkflowInstances({
    int? page = 1,
    int? pageSize = 20,
    String? status,
    String? workflowConfigId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowInstances,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #status: status,
            #workflowConfigId: workflowConfigId,
          },
        ),
        returnValue: _i4.Future<List<_i2.WorkflowInstanceModel>>.value(
            <_i2.WorkflowInstanceModel>[]),
      ) as _i4.Future<List<_i2.WorkflowInstanceModel>>);

  @override
  _i4.Future<_i2.WorkflowInstanceModel> performTransition(
    String? instanceId,
    _i2.WorkflowTransitionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performTransition,
          [
            instanceId,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.WorkflowInstanceModel>.value(
            _FakeWorkflowInstanceModel_0(
          this,
          Invocation.method(
            #performTransition,
            [
              instanceId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.WorkflowInstanceModel>);

  @override
  _i4.Future<List<_i2.WorkflowTransitionModel>> getAvailableTransitions(
          String? instanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTransitions,
          [instanceId],
        ),
        returnValue: _i4.Future<List<_i2.WorkflowTransitionModel>>.value(
            <_i2.WorkflowTransitionModel>[]),
      ) as _i4.Future<List<_i2.WorkflowTransitionModel>>);

  @override
  _i4.Future<List<_i2.WorkflowTransitionLogModel>> getTransitionHistory(
    String? instanceId, {
    int? page = 1,
    int? pageSize = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransitionHistory,
          [instanceId],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i2.WorkflowTransitionLogModel>>.value(
            <_i2.WorkflowTransitionLogModel>[]),
      ) as _i4.Future<List<_i2.WorkflowTransitionLogModel>>);

  @override
  _i4.Future<List<_i2.WorkflowConfigurationModel>> getWorkflowConfigurations({
    String? entityType,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowConfigurations,
          [],
          {
            #entityType: entityType,
            #isActive: isActive,
          },
        ),
        returnValue: _i4.Future<List<_i2.WorkflowConfigurationModel>>.value(
            <_i2.WorkflowConfigurationModel>[]),
      ) as _i4.Future<List<_i2.WorkflowConfigurationModel>>);

  @override
  _i4.Future<_i2.WorkflowConfigurationModel> getWorkflowConfiguration(
          String? configId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowConfiguration,
          [configId],
        ),
        returnValue: _i4.Future<_i2.WorkflowConfigurationModel>.value(
            _FakeWorkflowConfigurationModel_1(
          this,
          Invocation.method(
            #getWorkflowConfiguration,
            [configId],
          ),
        )),
      ) as _i4.Future<_i2.WorkflowConfigurationModel>);

  @override
  _i4.Future<_i2.WorkflowDashboardModel> getWorkflowDashboard({
    String? workflowConfigId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowDashboard,
          [],
          {
            #workflowConfigId: workflowConfigId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.WorkflowDashboardModel>.value(
            _FakeWorkflowDashboardModel_2(
          this,
          Invocation.method(
            #getWorkflowDashboard,
            [],
            {
              #workflowConfigId: workflowConfigId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.WorkflowDashboardModel>);

  @override
  _i4.Future<_i2.WorkflowInstanceModel> createWorkflowInstance({
    required String? workflowConfigId,
    required String? contentType,
    required String? objectId,
    Map<String, dynamic>? properties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkflowInstance,
          [],
          {
            #workflowConfigId: workflowConfigId,
            #contentType: contentType,
            #objectId: objectId,
            #properties: properties,
          },
        ),
        returnValue: _i4.Future<_i2.WorkflowInstanceModel>.value(
            _FakeWorkflowInstanceModel_0(
          this,
          Invocation.method(
            #createWorkflowInstance,
            [],
            {
              #workflowConfigId: workflowConfigId,
              #contentType: contentType,
              #objectId: objectId,
              #properties: properties,
            },
          ),
        )),
      ) as _i4.Future<_i2.WorkflowInstanceModel>);

  @override
  _i4.Future<_i2.WorkflowInstanceModel> updateWorkflowInstance(
    String? instanceId,
    Map<String, dynamic>? properties,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkflowInstance,
          [
            instanceId,
            properties,
          ],
        ),
        returnValue: _i4.Future<_i2.WorkflowInstanceModel>.value(
            _FakeWorkflowInstanceModel_0(
          this,
          Invocation.method(
            #updateWorkflowInstance,
            [
              instanceId,
              properties,
            ],
          ),
        )),
      ) as _i4.Future<_i2.WorkflowInstanceModel>);
}
