from typing import Dict, Any
from apps.resume_intelligence.context import ResumeContext
from apps.resume_intelligence.pipeline import ResumePipeline
from .review_models import ReviewResult
from .review_rules import ResumeReviewRules

class ResumeReviewService:
    """
    Consumes ResumeContext generated by the Resume Intelligence pipeline
    and returns a structured ReviewResult Payload for the Action Center.
    """
    
    def __init__(self):
        self.pipeline = ResumePipeline()
        self.rules = ResumeReviewRules()

    def analyze(self, raw_resume_data: Dict[str, Any]) -> ReviewResult:
        """
        Executes the Resume Intelligence pipeline on the raw data,
        then evaluates the enriched context using Business Rules.
        """
        # 1. Initialize Context
        context = ResumeContext(resume_data=raw_resume_data)
        
        # 2. Run Intelligence Pipeline (Normalize, Classify, etc.)
        context = self.pipeline.execute(context)
        
        # 3. Evaluate Context using Review Rules
        categories, warnings, recommendations, top_action = self.rules.evaluate(context)
        
        # 4. Calculate Final Score & Status
        overall_score = self.rules.calculate_overall_score(categories)
        status = self.rules.get_status(overall_score)
        
        # 5. Build Result
        result = ReviewResult(
            overall_score=overall_score,
            status=status,
            confidence="98%",
            based_on=["Grammar Rules", "Semantic Analysis", "ATS Rules", "Structure Analysis"],
            categories=categories,
            top_action=top_action,
            warnings=warnings,
            recommendations=recommendations,
        )
        
        return result
