# Generated by Django 4.2.16 on 2026-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('register', 'Register'), ('cv_created', 'CV Created'), ('cv_updated', 'CV Updated'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('account_deleted', 'Account Deleted'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('account_deactivated', 'Account Deactivated'), ('password_changed', 'Password Changed'), ('deletion_requested', 'Deletion Requested')], db_index=True, max_length=30),
        ),
    ]
