# Generated by Django 4.2.16 on 2026-05-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_email_verification_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
