// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/notifications/presentation/providers/notification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:educv/features/notifications/domain/notification_repository.dart'
    as _i3;
import 'package:educv/features/notifications/models/notification_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationModel_0 extends _i1.SmartFake
    implements _i2.NotificationModel {
  _FakeNotificationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationStatsModel_1 extends _i1.SmartFake
    implements _i2.NotificationStatsModel {
  _FakeNotificationStatsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationPreferencesModel_2 extends _i1.SmartFake
    implements _i2.NotificationPreferencesModel {
  _FakeNotificationPreferencesModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i3.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.NotificationModel>> getNotifications({
    String? type,
    String? status,
    bool? unreadOnly,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #type: type,
            #status: status,
            #unreadOnly: unreadOnly,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.NotificationModel>>.value(
            <_i2.NotificationModel>[]),
      ) as _i4.Future<List<_i2.NotificationModel>>);

  @override
  _i4.Future<_i2.NotificationModel> getNotification(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotification,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.NotificationModel>.value(_FakeNotificationModel_0(
          this,
          Invocation.method(
            #getNotification,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.NotificationModel>);

  @override
  _i4.Future<bool> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> markMultipleAsRead(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #markMultipleAsRead,
          [ids],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.NotificationStatsModel> getNotificationStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStats,
          [],
        ),
        returnValue: _i4.Future<_i2.NotificationStatsModel>.value(
            _FakeNotificationStatsModel_1(
          this,
          Invocation.method(
            #getNotificationStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.NotificationStatsModel>);

  @override
  _i4.Future<_i2.NotificationPreferencesModel> getPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _i4.Future<_i2.NotificationPreferencesModel>.value(
            _FakeNotificationPreferencesModel_2(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        )),
      ) as _i4.Future<_i2.NotificationPreferencesModel>);

  @override
  _i4.Future<_i2.NotificationPreferencesModel> updatePreferences(
          _i2.NotificationPreferencesModel? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i4.Future<_i2.NotificationPreferencesModel>.value(
            _FakeNotificationPreferencesModel_2(
          this,
          Invocation.method(
            #updatePreferences,
            [preferences],
          ),
        )),
      ) as _i4.Future<_i2.NotificationPreferencesModel>);
}
