# Generated by Django 4.2.16 on 2026-05-16 13:27

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0004_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Sequential version number')),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('bulk_update', 'Bulk Update')], max_length=15)),
                ('change_summary', models.CharField(blank=True, help_text='Brief description of what changed', max_length=255)),
                ('cv_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Complete serialized CV data at this version')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('data_size', models.IntegerField(default=0, help_text='Size of cv_data in bytes')),
                ('fields_changed', models.JSONField(default=list, help_text='List of field names that changed in this version')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_versions_created', to=settings.AUTH_USER_MODEL)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv.cvprofile')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='version_history.cvversion')),
            ],
            options={
                'db_table': 'cv_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VersionConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_versions_per_cv', models.IntegerField(default=50, help_text='Maximum number of versions to keep per CV (0 = unlimited)')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Automatically cleanup old versions when limit exceeded')),
                ('track_minor_changes', models.BooleanField(default=True, help_text='Track minor changes like formatting updates')),
                ('compression_enabled', models.BooleanField(default=False, help_text='Enable compression for version data (future feature)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'version_configurations',
            },
        ),
        migrations.CreateModel(
            name='VersionCleanupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versions_deleted', models.IntegerField(default=0)),
                ('oldest_version_kept', models.IntegerField(blank=True, null=True)),
                ('cleanup_reason', models.CharField(default='max_versions_exceeded', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_logs', to='cv.cvprofile')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'version_cleanup_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_type', models.CharField(choices=[('field_change', 'Field Change'), ('section_add', 'Section Added'), ('section_remove', 'Section Removed'), ('section_modify', 'Section Modified')], max_length=15)),
                ('field_path', models.CharField(help_text="Dot-notation path to changed field (e.g., 'profile.summary')", max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_from', to='version_history.cvversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_to', to='version_history.cvversion')),
            ],
            options={
                'db_table': 'version_diffs',
                'ordering': ['field_path'],
                'indexes': [models.Index(fields=['from_version', 'to_version'], name='idx_version_diffs_versions'), models.Index(fields=['diff_type'], name='idx_version_diffs_type')],
            },
        ),
        migrations.CreateModel(
            name='VersionAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('view_version', 'View Version'), ('view_history', 'View History'), ('restore_version', 'Restore Version'), ('compare_versions', 'Compare Versions'), ('delete_version', 'Delete Version')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict, help_text='Additional action-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_actions', to='cv.cvprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_actions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='version_history.cvversion')),
            ],
            options={
                'db_table': 'version_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cv_profile', '-created_at'], name='idx_version_actions_cv'), models.Index(fields=['action_type'], name='idx_version_actions_type'), models.Index(fields=['user', '-created_at'], name='idx_version_actions_user')],
            },
        ),
        migrations.AddIndex(
            model_name='cvversion',
            index=models.Index(fields=['cv_profile', '-version_number'], name='idx_cv_versions_profile'),
        ),
        migrations.AddIndex(
            model_name='cvversion',
            index=models.Index(fields=['changed_at'], name='idx_cv_versions_changed_at'),
        ),
        migrations.AddIndex(
            model_name='cvversion',
            index=models.Index(fields=['change_type'], name='idx_cv_versions_change_type'),
        ),
        migrations.AddConstraint(
            model_name='cvversion',
            constraint=models.UniqueConstraint(fields=('cv_profile', 'version_number'), name='unique_version_per_cv'),
        ),
    ]
