// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/template_engine/presentation/widgets/template_engine_widgets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:educv/features/data/models/industry_model.dart' as _i3;
import 'package:educv/features/data/models/role_model.dart' as _i4;
import 'package:educv/features/data/models/template_category_model.dart' as _i5;
import 'package:educv/features/data/models/template_model.dart' as _i6;
import 'package:educv/features/template_engine/presentation/providers/template_engine_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TemplateEngineProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateEngineProvider extends _i1.Mock
    implements _i2.TemplateEngineProvider {
  MockTemplateEngineProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.IndustryModel> get industries => (super.noSuchMethod(
        Invocation.getter(#industries),
        returnValue: <_i3.IndustryModel>[],
      ) as List<_i3.IndustryModel>);

  @override
  List<_i4.RoleModel> get roles => (super.noSuchMethod(
        Invocation.getter(#roles),
        returnValue: <_i4.RoleModel>[],
      ) as List<_i4.RoleModel>);

  @override
  List<_i5.TemplateCategoryModel> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i5.TemplateCategoryModel>[],
      ) as List<_i5.TemplateCategoryModel>);

  @override
  List<_i6.TemplateModel> get templates => (super.noSuchMethod(
        Invocation.getter(#templates),
        returnValue: <_i6.TemplateModel>[],
      ) as List<_i6.TemplateModel>);

  @override
  List<_i6.TemplateModel> get recommendedTemplates => (super.noSuchMethod(
        Invocation.getter(#recommendedTemplates),
        returnValue: <_i6.TemplateModel>[],
      ) as List<_i6.TemplateModel>);

  @override
  List<_i6.TemplateModel> get popularTemplates => (super.noSuchMethod(
        Invocation.getter(#popularTemplates),
        returnValue: <_i6.TemplateModel>[],
      ) as List<_i6.TemplateModel>);

  @override
  List<_i6.TemplateModel> get recentTemplates => (super.noSuchMethod(
        Invocation.getter(#recentTemplates),
        returnValue: <_i6.TemplateModel>[],
      ) as List<_i6.TemplateModel>);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get hasActiveFilters => (super.noSuchMethod(
        Invocation.getter(#hasActiveFilters),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadIndustries() => (super.noSuchMethod(
        Invocation.method(
          #loadIndustries,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadRoles({String? industrySlug}) => (super.noSuchMethod(
        Invocation.method(
          #loadRoles,
          [],
          {#industrySlug: industrySlug},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadCategories() => (super.noSuchMethod(
        Invocation.method(
          #loadCategories,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadTemplates() => (super.noSuchMethod(
        Invocation.method(
          #loadTemplates,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadRecommendedTemplates({int? limit = 6}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRecommendedTemplates,
          [],
          {#limit: limit},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadPopularTemplates({
    int? limit = 6,
    int? days = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPopularTemplates,
          [],
          {
            #limit: limit,
            #days: days,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadUserPreferences() => (super.noSuchMethod(
        Invocation.method(
          #loadUserPreferences,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void setCategory(String? category) => super.noSuchMethod(
        Invocation.method(
          #setCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setIndustry(String? industry) => super.noSuchMethod(
        Invocation.method(
          #setIndustry,
          [industry],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRole(String? role) => super.noSuchMethod(
        Invocation.method(
          #setRole,
          [role],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayout(String? layout) => super.noSuchMethod(
        Invocation.method(
          #setLayout,
          [layout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPremiumFilter(bool? isPremium) => super.noSuchMethod(
        Invocation.method(
          #setPremiumFilter,
          [isPremium],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> selectTemplate(String? slug) => (super.noSuchMethod(
        Invocation.method(
          #selectTemplate,
          [slug],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> previewTemplate(String? slug) => (super.noSuchMethod(
        Invocation.method(
          #previewTemplate,
          [slug],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> renderTemplate(
    String? slug, {
    Map<String, dynamic>? customBranding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renderTemplate,
          [slug],
          {#customBranding: customBranding},
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> toggleFavorite(_i6.TemplateModel? template) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [template],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isFavorite(_i6.TemplateModel? template) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [template],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> updatePreferences(Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addToRecent(_i6.TemplateModel? template) => super.noSuchMethod(
        Invocation.method(
          #addToRecent,
          [template],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelectedTemplate() => super.noSuchMethod(
        Invocation.method(
          #clearSelectedTemplate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
