// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/analytics/presentation/providers/analytics_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:educv/features/analytics/data/models/analytics_models.dart'
    as _i2;
import 'package:educv/features/analytics/domain/analytics_repository.dart'
    as _i4;
import 'package:educv/features/cv_intelligence/data/models/cv_intelligence_models.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalyticsDashboardModel_0 extends _i1.SmartFake
    implements _i2.AnalyticsDashboardModel {
  _FakeAnalyticsDashboardModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrendAnalysisModel_1 extends _i1.SmartFake
    implements _i2.TrendAnalysisModel {
  _FakeTrendAnalysisModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBenchmarkingDataModel_2 extends _i1.SmartFake
    implements _i3.BenchmarkingDataModel {
  _FakeBenchmarkingDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompletionStatisticsModel_3 extends _i1.SmartFake
    implements _i2.CompletionStatisticsModel {
  _FakeCompletionStatisticsModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScoreSnapshotModel_4 extends _i1.SmartFake
    implements _i2.ScoreSnapshotModel {
  _FakeScoreSnapshotModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepository extends _i1.Mock
    implements _i4.AnalyticsRepository {
  MockAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AnalyticsDashboardModel> getDashboardData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboardData,
          [],
        ),
        returnValue: _i5.Future<_i2.AnalyticsDashboardModel>.value(
            _FakeAnalyticsDashboardModel_0(
          this,
          Invocation.method(
            #getDashboardData,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AnalyticsDashboardModel>);

  @override
  _i5.Future<List<_i2.ScoreSnapshotModel>> getScoreSnapshots({
    String? snapshotType,
    bool? submissionReady,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreSnapshots,
          [],
          {
            #snapshotType: snapshotType,
            #submissionReady: submissionReady,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i2.ScoreSnapshotModel>>.value(
            <_i2.ScoreSnapshotModel>[]),
      ) as _i5.Future<List<_i2.ScoreSnapshotModel>>);

  @override
  _i5.Future<_i2.TrendAnalysisModel> getTrendAnalysis({
    required int? days,
    String? metric,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendAnalysis,
          [],
          {
            #days: days,
            #metric: metric,
          },
        ),
        returnValue:
            _i5.Future<_i2.TrendAnalysisModel>.value(_FakeTrendAnalysisModel_1(
          this,
          Invocation.method(
            #getTrendAnalysis,
            [],
            {
              #days: days,
              #metric: metric,
            },
          ),
        )),
      ) as _i5.Future<_i2.TrendAnalysisModel>);

  @override
  _i5.Future<_i3.BenchmarkingDataModel> getBenchmarkingData(
          {List<String>? groupTypes}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBenchmarkingData,
          [],
          {#groupTypes: groupTypes},
        ),
        returnValue: _i5.Future<_i3.BenchmarkingDataModel>.value(
            _FakeBenchmarkingDataModel_2(
          this,
          Invocation.method(
            #getBenchmarkingData,
            [],
            {#groupTypes: groupTypes},
          ),
        )),
      ) as _i5.Future<_i3.BenchmarkingDataModel>);

  @override
  _i5.Future<_i2.CompletionStatisticsModel> getCompletionStatistics({
    String? groupType,
    required int? timePeriod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletionStatistics,
          [],
          {
            #groupType: groupType,
            #timePeriod: timePeriod,
          },
        ),
        returnValue: _i5.Future<_i2.CompletionStatisticsModel>.value(
            _FakeCompletionStatisticsModel_3(
          this,
          Invocation.method(
            #getCompletionStatistics,
            [],
            {
              #groupType: groupType,
              #timePeriod: timePeriod,
            },
          ),
        )),
      ) as _i5.Future<_i2.CompletionStatisticsModel>);

  @override
  _i5.Future<_i2.ScoreSnapshotModel> createSnapshot({
    required String? snapshotType,
    String? triggerEvent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSnapshot,
          [],
          {
            #snapshotType: snapshotType,
            #triggerEvent: triggerEvent,
          },
        ),
        returnValue:
            _i5.Future<_i2.ScoreSnapshotModel>.value(_FakeScoreSnapshotModel_4(
          this,
          Invocation.method(
            #createSnapshot,
            [],
            {
              #snapshotType: snapshotType,
              #triggerEvent: triggerEvent,
            },
          ),
        )),
      ) as _i5.Future<_i2.ScoreSnapshotModel>);
}
