# Generated by Django 4.2.16 on 2026-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('cv', 'language'), name='unique_language_per_cv'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('cv', 'name'), name='unique_skill_per_cv'),
        ),
    ]
