# Generated by Django 4.2.16 on 2026-04-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv.cvprofile'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('cv', 'name'), name='unique_skill_per_cv'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('cv', 'language'), name='unique_language_per_cv'),
        ),
        migrations.AddIndex(
            model_name='generatedcv',
            index=models.Index(fields=['template'], name='idx_generatedcv_template'),
        ),
        migrations.AddIndex(
            model_name='generatedcv',
            index=models.Index(fields=['generated_at'], name='idx_generatedcv_generated_at'),
        ),
    ]
