# Generated by Django 4.2.16 on 2026-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_language_unique_language_per_cv_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generatedcv',
            index=models.Index(fields=['template'], name='idx_generatedcv_template'),
        ),
        migrations.AddIndex(
            model_name='generatedcv',
            index=models.Index(fields=['generated_at'], name='idx_generatedcv_generated_at'),
        ),
    ]
