# Generated by Django 4.2.16 on 2026-06-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_engine', '0001_initial'),
        ('cv', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='target_role',
            field=models.ForeignKey(blank=True, help_text='The role the student is targeting with this CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_profiles', to='template_engine.role'),
        ),
    ]
