# Generated by Django 4.2.16 on 2026-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_add_target_role_to_cvprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='custom_role_name',
            field=models.CharField(blank=True, default='', help_text='Custom role/major name when not in the seeded roles list', max_length=100),
        ),
    ]
