# Generated by Django 4.2.16 on 2026-05-17 00:22

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications globally')),
                ('email_rate_limit', models.IntegerField(default=100, help_text='Maximum emails per hour per user')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('max_notifications_per_user', models.IntegerField(default=1000, help_text='Maximum notifications to keep per user')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Automatically cleanup old notifications')),
                ('cleanup_after_days', models.IntegerField(default=90, help_text='Delete read notifications after N days')),
                ('batch_size', models.IntegerField(default=100, help_text='Batch size for bulk operations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_configurations',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('cv_updates_email', models.BooleanField(default=True)),
                ('cv_updates_in_app', models.BooleanField(default=True)),
                ('workflow_changes_email', models.BooleanField(default=True)),
                ('workflow_changes_in_app', models.BooleanField(default=True)),
                ('system_notifications_email', models.BooleanField(default=True)),
                ('system_notifications_in_app', models.BooleanField(default=True)),
                ('security_alerts_email', models.BooleanField(default=True)),
                ('security_alerts_in_app', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='immediate', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('cv_created', 'CV Created'), ('cv_updated', 'CV Updated'), ('cv_completed', 'CV Completed'), ('pdf_generated', 'PDF Generated'), ('workflow_changed', 'Workflow Status Changed'), ('version_restored', 'Version Restored'), ('analysis_completed', 'Analysis Completed'), ('system_maintenance', 'System Maintenance'), ('account_updated', 'Account Updated'), ('security_alert', 'Security Alert'), ('custom', 'Custom Notification')], db_index=True, max_length=30)),
                ('title_template', models.CharField(help_text='Template for notification title (supports variables)', max_length=255)),
                ('message_template', models.TextField(help_text='Template for notification message (supports variables)')),
                ('email_subject_template', models.CharField(blank=True, help_text='Email subject template (optional, uses title if empty)', max_length=255)),
                ('email_html_template', models.TextField(blank=True, help_text='HTML email template (optional)')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_user_preference', models.BooleanField(default=True, help_text='Check user preferences before sending')),
                ('available_variables', models.JSONField(default=dict, help_text='Documentation of available template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'indexes': [models.Index(fields=['notification_type'], name='idx_notif_templates_type'), models.Index(fields=['is_active'], name='idx_notif_templates_active')],
            },
        ),
        migrations.CreateModel(
            name='NotificationCleanupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_deleted', models.IntegerField(default=0)),
                ('batches_deleted', models.IntegerField(default=0)),
                ('events_deleted', models.IntegerField(default=0)),
                ('cleanup_reason', models.CharField(max_length=100)),
                ('older_than_days', models.IntegerField(blank=True, null=True)),
                ('status_filter', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_cleanup_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('context_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Context data for template rendering')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('total_notifications', models.IntegerField(default=0)),
                ('sent_notifications', models.IntegerField(default=0)),
                ('failed_notifications', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send the batch (null = immediate)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_batches', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email')], max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('context_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional context data for the notification')),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_html_content', models.TextField(blank=True)),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('notification_created', 'Notification Created'), ('notification_sent', 'Notification Sent'), ('notification_delivered', 'Notification Delivered'), ('notification_read', 'Notification Read'), ('notification_failed', 'Notification Failed'), ('batch_created', 'Batch Created'), ('batch_started', 'Batch Started'), ('batch_completed', 'Batch Completed'), ('preferences_updated', 'Preferences Updated'), ('template_updated', 'Template Updated')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional event-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.notificationbatch')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='idx_notif_events_type'), models.Index(fields=['user', '-created_at'], name='idx_notif_events_user'), models.Index(fields=['created_at'], name='idx_notif_events_created')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['status'], name='idx_notif_batches_status'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['scheduled_at'], name='idx_notif_batches_scheduled'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='idx_notifications_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='idx_notifications_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='idx_notifications_type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='idx_notifications_channel'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='idx_notifications_created'),
        ),
    ]
