"""
Student serializers for admin dashboard.
"""
from rest_framework import serializers
from apps.users.models import User
from apps.cv.models import CVProfile, GeneratedCV


class StudentListSerializer(serializers.ModelSerializer):
    """Serializer for student list view - summary fields only"""
    
    cv_completion_percentage = serializers.SerializerMethodField()
    total_cvs_generated = serializers.SerializerMethodField()
    
    class Meta:
        model = User
        fields = [
            'id', 'full_name', 'email', 'student_id', 'status',
            'created_at', 'last_login_at', 'cv_completion_percentage',
            'total_cvs_generated'
        ]
    
    def get_cv_completion_percentage(self, obj):
        """Get CV completion percentage"""
        try:
            return obj.cv_profile.completion_percentage
        except CVProfile.DoesNotExist:
            return 0
    
    def get_total_cvs_generated(self, obj):
        """Use prefetched generated_cvs to avoid N+1 queries."""
        try:
            # len() uses the prefetch cache; .count() would fire a new query
            return len(obj.cv_profile.generated_cvs.all())
        except CVProfile.DoesNotExist:
            return 0


class StudentDetailSerializer(serializers.ModelSerializer):
    """Serializer for student detail view - full fields"""
    
    cv_completion_percentage = serializers.SerializerMethodField()
    total_cvs_generated = serializers.SerializerMethodField()
    generated_cvs_history = serializers.SerializerMethodField()
    consent_info = serializers.SerializerMethodField()
    deletion_request_info = serializers.SerializerMethodField()
    
    class Meta:
        model = User
        fields = [
            'id', 'full_name', 'email', 'student_id', 'status', 'role',
            'created_at', 'updated_at', 'last_login_at',
            'data_processing_consent', 'data_processing_consent_date',
            'marketing_consent', 'marketing_consent_date',
            'terms_consent', 'terms_consent_date',
            'deletion_requested_at', 'is_deleted', 'deleted_at',
            'cv_completion_percentage', 'total_cvs_generated',
            'generated_cvs_history', 'consent_info', 'deletion_request_info'
        ]
    
    def get_cv_completion_percentage(self, obj):
        """Get CV completion percentage"""
        try:
            return obj.cv_profile.completion_percentage
        except CVProfile.DoesNotExist:
            return 0
    
    def get_total_cvs_generated(self, obj):
        """Get total number of CVs generated by this student"""
        try:
            return obj.cv_profile.generated_cvs.count()
        except CVProfile.DoesNotExist:
            return 0
    
    def get_generated_cvs_history(self, obj):
        """Get recent CV generation history (most recent 20)"""
        try:
            recent_cvs = obj.cv_profile.generated_cvs.order_by('-generated_at')[:20]
            return [
                {
                    'id': cv.id,
                    'template': cv.template,
                    'generated_at': cv.generated_at,
                    'download_count': cv.download_count,
                    'file_size': cv.file_size,
                }
                for cv in recent_cvs
            ]
        except CVProfile.DoesNotExist:
            return []
    
    def get_consent_info(self, obj):
        """Get consent status summary"""
        return {
            'all_consents_given': all([
                obj.data_processing_consent,
                obj.terms_consent
                # marketing_consent is optional — not required for compliance
            ]),
            'data_processing': {
                'given': obj.data_processing_consent,
                'date': obj.data_processing_consent_date
            },
            'marketing': {
                'given': obj.marketing_consent,
                'date': obj.marketing_consent_date
            },
            'terms': {
                'given': obj.terms_consent,
                'date': obj.terms_consent_date
            }
        }
    
    def get_deletion_request_info(self, obj):
        """Get deletion request information"""
        if not obj.deletion_requested_at:
            return None
        
        from django.utils import timezone
        days_since_request = (timezone.now() - obj.deletion_requested_at).days
        
        return {
            'requested_at': obj.deletion_requested_at,
            'days_since_request': days_since_request,
            'is_processed': obj.is_deleted,
            'processed_at': obj.deleted_at
        }


class StudentStatusUpdateSerializer(serializers.Serializer):
    """Serializer for updating student status"""
    
    status = serializers.ChoiceField(choices=User.Status.choices)
    reason = serializers.CharField(max_length=500, required=False, allow_blank=True)
    
    def validate(self, data):
        """Validate status transitions"""
        current_status = self.instance.status if self.instance else None
        new_status = data['status']
        
        # Define allowed transitions
        allowed_transitions = {
            User.Status.ACTIVE: [User.Status.SUSPENDED, User.Status.DEACTIVATED],
            User.Status.SUSPENDED: [User.Status.ACTIVE, User.Status.DEACTIVATED],
            User.Status.DEACTIVATED: [User.Status.ACTIVE],
        }
        
        if current_status and new_status not in allowed_transitions.get(current_status, []):
            raise serializers.ValidationError(
                f"Cannot transition from {current_status} to {new_status}"
            )
        
        return data


class DeletionRequestSerializer(serializers.ModelSerializer):
    """Serializer for deletion requests list"""
    
    days_since_request = serializers.SerializerMethodField()
    
    class Meta:
        model = User
        fields = [
            'id', 'full_name', 'email', 'student_id',
            'deletion_requested_at', 'days_since_request'
        ]
    
    def get_days_since_request(self, obj):
        """Calculate days since deletion was requested"""
        if not obj.deletion_requested_at:
            return 0
        
        from django.utils import timezone
        return (timezone.now() - obj.deletion_requested_at).days