// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/cv_intelligence/presentation/providers/cv_intelligence_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:educv/features/cv_intelligence/domain/cv_intelligence_repository.dart'
    as _i3;
import 'package:educv/features/cv_intelligence/presentation/models/cv_intelligence_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCVAnalysisModel_0 extends _i1.SmartFake
    implements _i2.CVAnalysisModel {
  _FakeCVAnalysisModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalysisHistoryModel_1 extends _i1.SmartFake
    implements _i2.AnalysisHistoryModel {
  _FakeAnalysisHistoryModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubmissionReadinessModel_2 extends _i1.SmartFake
    implements _i2.SubmissionReadinessModel {
  _FakeSubmissionReadinessModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBenchmarkingDataModel_3 extends _i1.SmartFake
    implements _i2.BenchmarkingDataModel {
  _FakeBenchmarkingDataModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CVIntelligenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCVIntelligenceRepository extends _i1.Mock
    implements _i3.CVIntelligenceRepository {
  MockCVIntelligenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CVAnalysisModel?> getLatestAnalysis() => (super.noSuchMethod(
        Invocation.method(
          #getLatestAnalysis,
          [],
        ),
        returnValue: _i4.Future<_i2.CVAnalysisModel?>.value(),
      ) as _i4.Future<_i2.CVAnalysisModel?>);

  @override
  _i4.Future<_i2.CVAnalysisModel> analyzeCV({Map<String, dynamic>? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeCV,
          [],
          {#options: options},
        ),
        returnValue:
            _i4.Future<_i2.CVAnalysisModel>.value(_FakeCVAnalysisModel_0(
          this,
          Invocation.method(
            #analyzeCV,
            [],
            {#options: options},
          ),
        )),
      ) as _i4.Future<_i2.CVAnalysisModel>);

  @override
  _i4.Future<_i2.AnalysisHistoryModel> getAnalysisHistory({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalysisHistory,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.AnalysisHistoryModel>.value(
            _FakeAnalysisHistoryModel_1(
          this,
          Invocation.method(
            #getAnalysisHistory,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.AnalysisHistoryModel>);

  @override
  _i4.Future<List<_i2.RecommendationModel>> getRecommendations({
    String? category,
    String? priority,
    bool? includeImplemented = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendations,
          [],
          {
            #category: category,
            #priority: priority,
            #includeImplemented: includeImplemented,
          },
        ),
        returnValue: _i4.Future<List<_i2.RecommendationModel>>.value(
            <_i2.RecommendationModel>[]),
      ) as _i4.Future<List<_i2.RecommendationModel>>);

  @override
  _i4.Future<void> markRecommendationImplemented(String? recommendationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationImplemented,
          [recommendationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SubmissionReadinessModel> getSubmissionReadiness() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissionReadiness,
          [],
        ),
        returnValue: _i4.Future<_i2.SubmissionReadinessModel>.value(
            _FakeSubmissionReadinessModel_2(
          this,
          Invocation.method(
            #getSubmissionReadiness,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SubmissionReadinessModel>);

  @override
  _i4.Future<_i2.BenchmarkingDataModel> getBenchmarkingData(
          {String? comparisonGroup}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBenchmarkingData,
          [],
          {#comparisonGroup: comparisonGroup},
        ),
        returnValue: _i4.Future<_i2.BenchmarkingDataModel>.value(
            _FakeBenchmarkingDataModel_3(
          this,
          Invocation.method(
            #getBenchmarkingData,
            [],
            {#comparisonGroup: comparisonGroup},
          ),
        )),
      ) as _i4.Future<_i2.BenchmarkingDataModel>);

  @override
  _i4.Future<Map<String, dynamic>> getAnalysisConfig() => (super.noSuchMethod(
        Invocation.method(
          #getAnalysisConfig,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.CVAnalysisModel> getAnalysisById(String? analysisId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalysisById,
          [analysisId],
        ),
        returnValue:
            _i4.Future<_i2.CVAnalysisModel>.value(_FakeCVAnalysisModel_0(
          this,
          Invocation.method(
            #getAnalysisById,
            [analysisId],
          ),
        )),
      ) as _i4.Future<_i2.CVAnalysisModel>);

  @override
  _i4.Future<bool> hasCVProfile() => (super.noSuchMethod(
        Invocation.method(
          #hasCVProfile,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> exportAnalysisReport() => (super.noSuchMethod(
        Invocation.method(
          #exportAnalysisReport,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #exportAnalysisReport,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getScoreProgression({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreProgression,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
