# Generated by Django 4.2.16 on 2026-05-17 00:22

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=15)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('group', 'Group'), ('user', 'User')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sample_count', models.IntegerField(default=0)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('std_deviation', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional aggregation metadata')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_aggregated_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('cached_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Cached calculation results')),
                ('calculation_time_ms', models.IntegerField(default=0)),
                ('data_size_bytes', models.IntegerField(default=0)),
                ('hit_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_cache',
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('score_calculation_enabled', models.BooleanField(default=True)),
                ('benchmarking_enabled', models.BooleanField(default=True)),
                ('trend_analysis_enabled', models.BooleanField(default=True)),
                ('daily_aggregation_enabled', models.BooleanField(default=True)),
                ('weekly_aggregation_enabled', models.BooleanField(default=True)),
                ('monthly_aggregation_enabled', models.BooleanField(default=True)),
                ('raw_data_retention_days', models.IntegerField(default=365)),
                ('aggregated_data_retention_days', models.IntegerField(default=1095)),
                ('peer_group_size', models.IntegerField(default=100, help_text='Number of peers to include in benchmarking calculations', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('calculation_weights', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Weights for different score components')),
                ('benchmarking_criteria', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Criteria for peer group selection')),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_configurations',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('snapshot_created', 'Snapshot Created'), ('benchmark_calculated', 'Benchmark Calculated'), ('trend_analyzed', 'Trend Analyzed'), ('metric_aggregated', 'Metric Aggregated'), ('group_updated', 'Group Updated'), ('configuration_changed', 'Configuration Changed'), ('data_cleanup', 'Data Cleanup'), ('calculation_error', 'Calculation Error')], max_length=25)),
                ('description', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_usage_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional event-specific data')),
                ('error_message', models.TextField(blank=True, default='')),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('education_level', 'Education Level'), ('field_of_study', 'Field of Study'), ('experience_years', 'Experience Years'), ('location', 'Location'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Criteria for group membership')),
                ('member_count', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_update', models.BooleanField(default=True, help_text='Automatically update group membership based on criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_benchmarking_groups',
                'ordering': ['group_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkingGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('current_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'analytics_benchmarking_memberships',
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric_type', models.CharField(choices=[('score', 'Score'), ('percentage', 'Percentage'), ('count', 'Count'), ('ratio', 'Ratio'), ('duration', 'Duration'), ('custom', 'Custom')], max_length=15)),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum'), ('average', 'Average'), ('median', 'Median'), ('min', 'Minimum'), ('max', 'Maximum'), ('count', 'Count'), ('percentile', 'Percentile')], max_length=15)),
                ('calculation_formula', models.TextField(help_text='Formula or method for calculating this metric')),
                ('source_fields', models.JSONField(default=list, help_text='List of source fields/models used in calculation')),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('decimal_places', models.IntegerField(default=2)),
                ('format_string', models.CharField(blank=True, default='', max_length=50)),
                ('is_benchmarkable', models.BooleanField(default=True)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_metric', models.BooleanField(default=False, help_text='System-defined metric that cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_metric_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_start', models.DateTimeField()),
                ('analysis_end', models.DateTimeField()),
                ('data_points', models.IntegerField(default=0)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable'), ('volatile', 'Volatile')], max_length=15)),
                ('trend_strength', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=15)),
                ('slope', models.DecimalField(decimal_places=6, help_text='Linear regression slope', max_digits=15)),
                ('r_squared', models.DecimalField(decimal_places=4, help_text='Coefficient of determination', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('absolute_change', models.DecimalField(decimal_places=6, max_digits=15)),
                ('percentage_change', models.DecimalField(decimal_places=4, max_digits=8)),
                ('volatility_score', models.DecimalField(decimal_places=4, help_text='Measure of score volatility', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('predicted_next_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('confidence_interval', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Confidence intervals for predictions')),
                ('analysis_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Detailed analysis results and intermediate calculations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='analytics.benchmarkinggroup')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='analytics.metricdefinition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_trend_analyses',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('triggered', 'Triggered'), ('scheduled', 'Scheduled')], max_length=15)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=100)),
                ('overall_score', models.IntegerField(help_text='Overall CV score at snapshot time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_percentage', models.IntegerField(help_text='CV completion percentage at snapshot time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profile_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('education_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('projects_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('submission_ready', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('percentile_rank', models.DecimalField(blank=True, decimal_places=2, help_text='Percentile rank among peers', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('peer_group_size', models.IntegerField(default=0)),
                ('metrics_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional calculated metrics and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_score_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='metricdefinition',
            index=models.Index(fields=['is_active'], name='idx_metrics_active'),
        ),
        migrations.AddIndex(
            model_name='metricdefinition',
            index=models.Index(fields=['metric_type'], name='idx_metrics_type'),
        ),
        migrations.AddField(
            model_name='benchmarkinggroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.benchmarkinggroup'),
        ),
        migrations.AddField(
            model_name='benchmarkinggroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benchmarkinggroup',
            name='users',
            field=models.ManyToManyField(related_name='benchmarking_groups', through='analytics.BenchmarkingGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsconfiguration',
            index=models.Index(fields=['is_active'], name='idx_analytics_config_active'),
        ),
        migrations.AddIndex(
            model_name='analyticsconfiguration',
            index=models.Index(fields=['is_default'], name='idx_analytics_config_default'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['cache_type'], name='idx_analytics_cache_type'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['expires_at'], name='idx_analytics_cache_expires'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['is_expired'], name='idx_analytics_cache_expired'),
        ),
        migrations.AddField(
            model_name='aggregatedmetric',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_metrics', to='analytics.benchmarkinggroup'),
        ),
        migrations.AddField(
            model_name='aggregatedmetric',
            name='metric_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_values', to='analytics.metricdefinition'),
        ),
        migrations.AddField(
            model_name='aggregatedmetric',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['user', 'metric_definition'], name='idx_trends_user_metric'),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['group', 'metric_definition'], name='idx_trends_group_metric'),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['trend_direction'], name='idx_trends_direction'),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['calculated_at'], name='idx_trends_calculated'),
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['user', '-created_at'], name='idx_snapshots_user_created'),
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['overall_score'], name='idx_snapshots_overall_score'),
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['percentile_rank'], name='idx_snapshots_percentile'),
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['created_at'], name='idx_snapshots_created'),
        ),
        migrations.AddIndex(
            model_name='benchmarkinggroupmembership',
            index=models.Index(fields=['group', 'is_active'], name='idx_memberships_group_active'),
        ),
        migrations.AddIndex(
            model_name='benchmarkinggroupmembership',
            index=models.Index(fields=['current_rank'], name='idx_memberships_rank'),
        ),
        migrations.AlterUniqueTogether(
            name='benchmarkinggroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='benchmarkinggroup',
            index=models.Index(fields=['group_type'], name='idx_bench_groups_type'),
        ),
        migrations.AddIndex(
            model_name='benchmarkinggroup',
            index=models.Index(fields=['is_active'], name='idx_bench_groups_active'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='idx_analytics_events_type'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', '-created_at'], name='idx_analytics_events_user'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at'], name='idx_analytics_events_created'),
        ),
        migrations.AddIndex(
            model_name='aggregatedmetric',
            index=models.Index(fields=['metric_definition', 'period'], name='idx_agg_metrics_def_period'),
        ),
        migrations.AddIndex(
            model_name='aggregatedmetric',
            index=models.Index(fields=['user', 'period_start'], name='idx_agg_metrics_user_period'),
        ),
        migrations.AddIndex(
            model_name='aggregatedmetric',
            index=models.Index(fields=['group', 'period_start'], name='idx_agg_metrics_group_period'),
        ),
        migrations.AddIndex(
            model_name='aggregatedmetric',
            index=models.Index(fields=['period_start'], name='idx_agg_metrics_period_start'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedmetric',
            unique_together={('metric_definition', 'period', 'scope', 'period_start', 'user', 'group')},
        ),
    ]
