# Generated by Django 4.2.16 on 2026-05-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(help_text='Type of entity this workflow applies to (e.g., cv_profile)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=dict, help_text='Workflow configuration including states, transitions, and rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_configurations',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=dict, help_text='Instance-specific properties and metadata')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'workflow_instances',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('state_type', models.CharField(choices=[('initial', 'Initial'), ('intermediate', 'Intermediate'), ('final', 'Final'), ('terminal', 'Terminal')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('properties', models.JSONField(default=dict, help_text='State-specific properties and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowconfiguration')),
            ],
            options={
                'db_table': 'workflow_states',
                'ordering': ['workflow_config', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of user roles allowed to perform this transition')),
                ('validation_rules', models.JSONField(default=dict, help_text='Validation rules that must pass for transition to be allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_comment', models.BooleanField(default=False)),
                ('auto_transition', models.BooleanField(default=False)),
                ('properties', models.JSONField(default=dict, help_text='Transition-specific properties and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.workflowstate')),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowconfiguration')),
            ],
            options={
                'db_table': 'workflow_transitions',
                'ordering': ['workflow_config', 'from_state', 'to_state'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional transition metadata and context')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_logs_from', to='workflow.workflowstate')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_transitions', to=settings.AUTH_USER_MODEL)),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_logs_to', to='workflow.workflowstate')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workflow.workflowtransition')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_transition_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('validation', 'Validation Rule'), ('condition', 'Condition Rule'), ('action', 'Action Rule')], max_length=15)),
                ('field_path', models.CharField(help_text='Dot-notation path to the field to validate (e.g., cv.completion_percentage)', max_length=200)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('contains', 'Contains'), ('in', 'In List'), ('exists', 'Exists'), ('custom', 'Custom Function')], max_length=15)),
                ('expected_value', models.JSONField(help_text='Expected value for comparison')),
                ('is_active', models.BooleanField(default=True)),
                ('error_message', models.CharField(help_text='Error message to display when rule fails', max_length=255)),
                ('properties', models.JSONField(default=dict, help_text='Additional rule properties and configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflow.workflowconfiguration')),
            ],
            options={
                'db_table': 'workflow_rules',
                'ordering': ['workflow_config', 'rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook'), ('internal', 'Internal Notification')], max_length=15)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text='Additional notification metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('transition_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.workflowtransitionlog')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='workflow.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowconfiguration'),
        ),
        migrations.AddIndex(
            model_name='workflowtransitionlog',
            index=models.Index(fields=['workflow_instance', '-performed_at'], name='workflow_tr_workflo_a33de6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransitionlog',
            index=models.Index(fields=['performed_by', '-performed_at'], name='workflow_tr_perform_1eb2da_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransitionlog',
            index=models.Index(fields=['result'], name='workflow_tr_result_4cb0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransitionlog',
            index=models.Index(fields=['performed_at'], name='workflow_tr_perform_bcc546_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow_config', 'is_active'], name='workflow_tr_workflo_7fd6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['from_state'], name='workflow_tr_from_st_d55c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['to_state'], name='workflow_tr_to_stat_8a2a93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow_config', 'from_state', 'to_state')},
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow_config', 'is_active'], name='workflow_st_workflo_fe01ac_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['state_type'], name='workflow_st_state_t_a0e2a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together={('workflow_config', 'code')},
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['workflow_config', 'is_active'], name='workflow_ru_workflo_42eb85_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['rule_type'], name='workflow_ru_rule_ty_20c22b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['workflow_instance', '-created_at'], name='workflow_no_workflo_0012e3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['recipient', 'status'], name='workflow_no_recipie_f90cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['status', 'created_at'], name='workflow_no_status_2b5190_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['workflow_config', 'current_state'], name='workflow_in_workflo_4eddd4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_in_content_a676aa_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['started_by'], name='workflow_in_started_91bf33_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['updated_at'], name='workflow_in_updated_4018c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='workflowconfiguration',
            index=models.Index(fields=['entity_type', 'is_active'], name='workflow_co_entity__2e424a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconfiguration',
            index=models.Index(fields=['is_default', 'is_active'], name='workflow_co_is_defa_c662b6_idx'),
        ),
    ]
