# Generated by Django 4.2.16 on 2026-05-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('too_short', 'Content Too Short'), ('weak_language', 'Weak Language Used'), ('no_quantification', 'Missing Numbers/Metrics'), ('poor_grammar', 'Grammar Issues'), ('missing_section', 'Missing Required Section'), ('incomplete_info', 'Incomplete Information')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('section_type', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Description of the issue')),
                ('suggestion', models.TextField(help_text='How to fix this issue')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resolved'], name='idx_issue_user_resolved'), models.Index(fields=['severity'], name='idx_issue_severity')],
            },
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0, help_text='Overall CV score (0-100)')),
                ('completeness_score', models.IntegerField(default=0, help_text='Completeness score (0-25)')),
                ('quality_score', models.IntegerField(default=0, help_text='Content quality score (0-40)')),
                ('skills_score', models.IntegerField(default=0, help_text='Skills relevance score (0-20)')),
                ('format_score', models.IntegerField(default=0, help_text='Format optimization score (0-15)')),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed feedback and suggestions')),
                ('grade', models.CharField(default='F', help_text='Letter grade (A-F)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_cv_analysis_user_date'), models.Index(fields=['overall_score'], name='idx_cv_analysis_score')],
            },
        ),
        migrations.CreateModel(
            name='ContentSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('summary', 'Professional Summary'), ('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications')], max_length=50)),
                ('suggestion_type', models.CharField(choices=[('content_enhancement', 'Content Enhancement'), ('weak_language', 'Weak Language Fix'), ('quantification', 'Add Quantification'), ('action_verbs', 'Improve Action Verbs'), ('length_improvement', 'Length Improvement')], max_length=50)),
                ('original_content', models.TextField(help_text='Original content before enhancement')),
                ('suggested_content', models.TextField(help_text='AI-enhanced content suggestion')),
                ('improvement_reason', models.TextField(help_text='Explanation of why this improvement helps')),
                ('applied', models.BooleanField(default=False, help_text='Whether user applied this suggestion')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'section_type'], name='idx_suggestion_user_section'), models.Index(fields=['applied'], name='idx_suggestion_applied')],
            },
        ),
    ]
