# Generated by Django 4.2.16 on 2026-05-16 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cv_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('profile_weight', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_weight', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('education_weight', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_weight', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('projects_weight', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_overall_score', models.IntegerField(default=60, help_text='Minimum overall score for submission readiness', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_section_scores', models.JSONField(default=dict, help_text='Minimum scores required for each section')),
                ('configuration_data', models.JSONField(default=dict, help_text='Additional configuration parameters')),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv_analysis_configurations',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('missing_content', 'Missing Content'), ('poor_formatting', 'Poor Formatting'), ('weak_language', 'Weak Language'), ('insufficient_detail', 'Insufficient Detail'), ('outdated_skills', 'Outdated Skills'), ('grammar_error', 'Grammar Error'), ('inconsistent_format', 'Inconsistent Format'), ('missing_quantification', 'Missing Quantification')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('section', models.CharField(choices=[('profile', 'Profile'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('languages', 'Languages'), ('certifications', 'Certifications'), ('overall', 'Overall')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('current_value', models.TextField(blank=True, default='')),
                ('suggested_value', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_analysis_issues',
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('content_enhancement', 'Content Enhancement'), ('quantification', 'Add Quantification'), ('action_verbs', 'Stronger Action Verbs'), ('skill_addition', 'Add Relevant Skills'), ('experience_detail', 'More Experience Detail'), ('achievement_focus', 'Focus on Achievements'), ('formatting_improvement', 'Formatting Improvement'), ('keyword_optimization', 'Keyword Optimization')], max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=10)),
                ('section', models.CharField(choices=[('profile', 'Profile'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('languages', 'Languages'), ('certifications', 'Certifications'), ('overall', 'Overall')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('example', models.TextField(blank=True, default='')),
                ('target_field', models.CharField(blank=True, default='', max_length=100)),
                ('current_content', models.TextField(blank=True, default='')),
                ('suggested_content', models.TextField(blank=True, default='')),
                ('expected_score_improvement', models.IntegerField(default=0, help_text='Expected score improvement if implemented', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_content_recommendations',
                'ordering': ['priority', '-expected_score_improvement', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contentsuggestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='validationissue',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='cvanalysis',
            new_name='cv_analyses_user_id_ca4024_idx',
            old_name='idx_cv_analysis_user_date',
        ),
        migrations.RenameIndex(
            model_name='cvanalysis',
            new_name='cv_analyses_overall_a32880_idx',
            old_name='idx_cv_analysis_score',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='completeness_score',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='format_score',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='quality_score',
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='critical_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='education_score',
            field=models.IntegerField(default=0, help_text='Education section quality score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='experience_score',
            field=models.IntegerField(default=0, help_text='Experience section quality score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='profile_score',
            field=models.IntegerField(default=0, help_text='Profile completeness and quality score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='projects_score',
            field=models.IntegerField(default=0, help_text='Projects section quality score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='submission_ready',
            field=models.BooleanField(default=False, help_text='Whether CV meets minimum submission standards'),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='total_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='total_recommendations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='analysis_data',
            field=models.JSONField(default=dict, help_text='Detailed analysis results and metrics'),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='grade',
            field=models.CharField(choices=[('excellent', 'Excellent (90-100)'), ('good', 'Good (75-89)'), ('average', 'Average (60-74)'), ('needs_improvement', 'Needs Improvement (40-59)'), ('poor', 'Poor (0-39)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='overall_score',
            field=models.IntegerField(help_text='Overall CV score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='skills_score',
            field=models.IntegerField(default=0, help_text='Skills section quality and relevance score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='cvanalysis',
            index=models.Index(fields=['grade'], name='cv_analyses_grade_d0665e_idx'),
        ),
        migrations.DeleteModel(
            name='ContentSuggestion',
        ),
        migrations.DeleteModel(
            name='ValidationIssue',
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cv_intelligence.cvanalysis'),
        ),
        migrations.AddField(
            model_name='analysisissue',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cv_intelligence.cvanalysis'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['analysis', 'priority'], name='cv_content__analysi_da923c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['section', 'recommendation_type'], name='cv_content__section_d334d7_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['applied', 'dismissed'], name='cv_content__applied_426ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisissue',
            index=models.Index(fields=['analysis', 'severity'], name='cv_analysis_analysi_df85fc_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisissue',
            index=models.Index(fields=['section', 'issue_type'], name='cv_analysis_section_6acde0_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisissue',
            index=models.Index(fields=['resolved'], name='cv_analysis_resolve_d18d60_idx'),
        ),
    ]
