# Generated by Django 4.2.16 on 2026-05-19 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_intelligence', '0002_enhance_analysis_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisissue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisissue',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cv_intelligence.cvanalysis'),
        ),
        migrations.AlterField(
            model_name='contentrecommendation',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cv_intelligence.cvanalysis'),
        ),
        migrations.CreateModel(
            name='CVAnalysisHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall CV score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=2, help_text='CV readiness score for job applications', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('readiness_grade', models.CharField(blank=True, help_text='Letter grade representation of readiness', max_length=20, null=True)),
                ('section_scores', models.JSONField(default=dict, help_text='Scores for each CV section (profile, experience, etc.)')),
                ('recommendations', models.JSONField(default=list, help_text='List of improvement recommendations')),
                ('strengths', models.JSONField(default=list, help_text='Identified CV strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='Identified areas for improvement')),
                ('analysis_version', models.CharField(default='1.0', help_text='Version of analysis algorithm used', max_length=20)),
                ('total_recommendations', models.IntegerField(default=0, help_text='Total number of recommendations generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV Analysis History',
                'verbose_name_plural': 'CV Analysis Histories',
                'db_table': 'cv_analysis_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='cv_analysis_user_id_3ee6c4_idx'), models.Index(fields=['overall_score'], name='cv_analysis_overall_9c803d_idx'), models.Index(fields=['created_at'], name='cv_analysis_created_54e17d_idx')],
            },
        ),
    ]
