# Generated by Django 4.2.16 on 2026-06-02 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('template_engine', '0001_initial'),
        ('cv_intelligence', '0003_analysisissue_user_contentrecommendation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleIntelligenceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_sections', models.JSONField(default=list, help_text='List of required CV section checks e.g. ["github", "projects"]')),
                ('priority_keywords', models.JSONField(default=list, help_text='Role-specific power keywords e.g. ["architected", "deployed", "scaled"]')),
                ('role_weak_patterns', models.JSONField(default=list, help_text='Role-specific weak phrases to penalize e.g. ["helped", "assisted"]')),
                ('recommended_metrics', models.JSONField(default=list, help_text='Metric types relevant to this role e.g. ["uptime", "latency", "users"]')),
                ('role_specific_summary_guidance', models.TextField(blank=True, default='', help_text='One-sentence guidance for what the summary should emphasize for this role')),
                ('icon', models.CharField(blank=True, default='briefcase', help_text='Lucide icon name for this role', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.OneToOneField(help_text='The role this intelligence configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_config', to='template_engine.role')),
            ],
            options={
                'db_table': 'cv_role_intelligence_configs',
            },
        ),
    ]
