# Generated by Django 4.2.16 on 2026-06-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_intelligence', '0005_data_integrity_layer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cvanalysis',
            new_name='cv_analyses_user_id_985f9e_idx',
            old_name='cv_analyses_user_is_latest_idx',
        ),
    ]
