// Mocks generated by Mockito 5.4.4 from annotations
// in educv/test/features/template_engine/presentation/providers/template_engine_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i4;
import 'package:educv/core/network/api_client.dart' as _i11;
import 'package:educv/features/data/models/industry_model.dart' as _i7;
import 'package:educv/features/data/models/role_model.dart' as _i8;
import 'package:educv/features/data/models/template_category_model.dart' as _i9;
import 'package:educv/features/data/models/template_model.dart' as _i2;
import 'package:educv/features/data/models/user_template_preference_model.dart'
    as _i3;
import 'package:educv/features/template_engine/domain/repositories/template_engine_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTemplateModel_0 extends _i1.SmartFake implements _i2.TemplateModel {
  _FakeTemplateModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserTemplatePreferenceModel_1 extends _i1.SmartFake
    implements _i3.UserTemplatePreferenceModel {
  _FakeUserTemplatePreferenceModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<T1> extends _i1.SmartFake implements _i4.Response<T1> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TemplateEngineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateEngineRepository extends _i1.Mock
    implements _i5.TemplateEngineRepository {
  MockTemplateEngineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.IndustryModel>> getIndustries() => (super.noSuchMethod(
        Invocation.method(
          #getIndustries,
          [],
        ),
        returnValue:
            _i6.Future<List<_i7.IndustryModel>>.value(<_i7.IndustryModel>[]),
      ) as _i6.Future<List<_i7.IndustryModel>>);

  @override
  _i6.Future<List<_i8.RoleModel>> getRoles({String? industrySlug}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoles,
          [],
          {#industrySlug: industrySlug},
        ),
        returnValue: _i6.Future<List<_i8.RoleModel>>.value(<_i8.RoleModel>[]),
      ) as _i6.Future<List<_i8.RoleModel>>);

  @override
  _i6.Future<List<_i9.TemplateCategoryModel>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<List<_i9.TemplateCategoryModel>>.value(
            <_i9.TemplateCategoryModel>[]),
      ) as _i6.Future<List<_i9.TemplateCategoryModel>>);

  @override
  _i6.Future<List<_i2.TemplateModel>> getTemplates({
    String? category,
    String? industry,
    String? role,
    String? layoutType,
    bool? isPremium,
    String? search,
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTemplates,
          [],
          {
            #category: category,
            #industry: industry,
            #role: role,
            #layoutType: layoutType,
            #isPremium: isPremium,
            #search: search,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<List<_i2.TemplateModel>>.value(<_i2.TemplateModel>[]),
      ) as _i6.Future<List<_i2.TemplateModel>>);

  @override
  _i6.Future<_i2.TemplateModel> getTemplate(String? slug) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTemplate,
          [slug],
        ),
        returnValue: _i6.Future<_i2.TemplateModel>.value(_FakeTemplateModel_0(
          this,
          Invocation.method(
            #getTemplate,
            [slug],
          ),
        )),
      ) as _i6.Future<_i2.TemplateModel>);

  @override
  _i6.Future<List<_i2.TemplateModel>> getRecommendedTemplates(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedTemplates,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<List<_i2.TemplateModel>>.value(<_i2.TemplateModel>[]),
      ) as _i6.Future<List<_i2.TemplateModel>>);

  @override
  _i6.Future<List<_i2.TemplateModel>> getPopularTemplates({
    int? limit = 10,
    int? days = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTemplates,
          [],
          {
            #limit: limit,
            #days: days,
          },
        ),
        returnValue:
            _i6.Future<List<_i2.TemplateModel>>.value(<_i2.TemplateModel>[]),
      ) as _i6.Future<List<_i2.TemplateModel>>);

  @override
  _i6.Future<String> previewTemplate(String? slug) => (super.noSuchMethod(
        Invocation.method(
          #previewTemplate,
          [slug],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #previewTemplate,
            [slug],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<Map<String, dynamic>> renderTemplate(
    String? slug, {
    Map<String, dynamic>? customBranding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renderTemplate,
          [slug],
          {#customBranding: customBranding},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> favoriteTemplate(String? slug) => (super.noSuchMethod(
        Invocation.method(
          #favoriteTemplate,
          [slug],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unfavoriteTemplate(String? slug) => (super.noSuchMethod(
        Invocation.method(
          #unfavoriteTemplate,
          [slug],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserTemplatePreferenceModel> getUserPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [],
        ),
        returnValue: _i6.Future<_i3.UserTemplatePreferenceModel>.value(
            _FakeUserTemplatePreferenceModel_1(
          this,
          Invocation.method(
            #getUserPreferences,
            [],
          ),
        )),
      ) as _i6.Future<_i3.UserTemplatePreferenceModel>);

  @override
  _i6.Future<_i3.UserTemplatePreferenceModel> updateUserPreferences(
          Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreferences,
          [preferences],
        ),
        returnValue: _i6.Future<_i3.UserTemplatePreferenceModel>.value(
            _FakeUserTemplatePreferenceModel_1(
          this,
          Invocation.method(
            #updateUserPreferences,
            [preferences],
          ),
        )),
      ) as _i6.Future<_i3.UserTemplatePreferenceModel>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i11.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<T>>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeAuthToken() => super.noSuchMethod(
        Invocation.method(
          #removeAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
