# Generated by Django 4.2.16 on 2026-05-17 00:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template_industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='template_engine.industry')),
            ],
            options={
                'db_table': 'template_roles',
                'ordering': ['industry__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('layout_type', models.CharField(choices=[('single_column', 'Single Column'), ('two_column', 'Two Column'), ('three_column', 'Three Column'), ('modern_grid', 'Modern Grid'), ('timeline', 'Timeline')], default='single_column', max_length=20)),
                ('html_template', models.TextField(help_text='HTML template content')),
                ('css_styles', models.TextField(blank=True, default='', help_text='CSS styles for template')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTemplatePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_order_preferences', models.JSONField(blank=True, default=dict)),
                ('hidden_sections', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='template_engine.template')),
                ('favorite_templates', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='template_engine.template')),
                ('preferred_industries', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='template_engine.industry')),
                ('preferred_roles', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='template_engine.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_template_preferences',
            },
        ),
        migrations.CreateModel(
            name='TemplatePerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_previews', models.IntegerField(default=0)),
                ('total_generations', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_render_time_ms', models.FloatField(blank=True, null=True)),
                ('avg_file_size_bytes', models.FloatField(blank=True, null=True)),
                ('favorite_count', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Preview to generation conversion rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='template_engine.template')),
            ],
            options={
                'db_table': 'template_performance_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='template_engine.templatecategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='templates', to='template_engine.industry'),
        ),
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='template_engine.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='templates', to='template_engine.role'),
        ),
        migrations.CreateModel(
            name='SectionConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('personal_info', 'Personal Information'), ('summary', 'Professional Summary'), ('education', 'Education'), ('experience', 'Work Experience'), ('skills', 'Skills'), ('languages', 'Languages'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('references', 'References'), ('custom', 'Custom Section')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('css_classes', models.CharField(blank=True, default='', max_length=200)),
                ('custom_html', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='template_engine.template')),
            ],
            options={
                'db_table': 'template_sections',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BrandingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#0ea5e9', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#1e293b', help_text='Hex color code', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('heading_font', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('font_size_base', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('margin_top', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('margin_bottom', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('section_spacing', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('custom_css', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='template_engine.template')),
            ],
            options={
                'db_table': 'template_branding',
            },
        ),
        migrations.CreateModel(
            name='TemplateUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('preview', 'Preview'), ('generate', 'Generate PDF'), ('download', 'Download'), ('favorite', 'Add to Favorites'), ('unfavorite', 'Remove from Favorites')], max_length=15)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('render_time_ms', models.IntegerField(blank=True, help_text='Rendering time in milliseconds', null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, help_text='Generated file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='template_engine.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'action'], name='idx_usage_template_action'), models.Index(fields=['user', 'created_at'], name='idx_usage_user_created'), models.Index(fields=['created_at'], name='idx_usage_created')],
            },
        ),
        migrations.CreateModel(
            name='TemplateRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('industry_based', 'Industry Based'), ('role_based', 'Role Based'), ('usage_based', 'Usage Pattern Based'), ('collaborative', 'Collaborative Filtering'), ('content_based', 'Content Based')], max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reasoning', models.TextField(blank=True, default='')),
                ('algorithm_version', models.CharField(default='1.0', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='template_engine.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_recommendations',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'confidence_score'], name='idx_rec_user_confidence'), models.Index(fields=['template', 'recommendation_type'], name='idx_rec_template_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='templateperformancemetric',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='unique_template_metric_per_date'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['status', 'is_premium'], name='idx_template_status_premium'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category', 'status'], name='idx_template_category_status'),
        ),
        migrations.AddConstraint(
            model_name='sectionconfiguration',
            constraint=models.UniqueConstraint(fields=('template', 'section_type'), name='unique_section_per_template'),
        ),
    ]
